# Numpy

lesson 2 
**numpy array attriputes and indexing**

In [1]:
import numpy as np

## Numpy Array Attributes
- **what is the attriputes that used to get info about array**
    - EX:
        - ndim    => return dimentional number.
        - shape   => return the shape of array.
        - size    => return size of my array.


In [2]:
z = np.zeros((2,4,4))
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [3]:
z.ndim

3

In [4]:
z.shape

(2, 4, 4)

In [5]:
z.size

32

----------------------------

----------------------------

## Numpy array indexing

In [7]:
x1 = np.array([1,2,3,4,5,1,2,3])
x1

array([1, 2, 3, 4, 5, 1, 2, 3])

In [8]:

# get first elemint
x1[0]

np.int64(1)

In [9]:

# get sec elemint
x1[1]

np.int64(2)

In [10]:
x1[-1]

np.int64(3)

--------------

**indexing mulit dimentional**

In [11]:
x2 = np.array([[11,2,31,33],[12,31,11,34]])
x2

array([[11,  2, 31, 33],
       [12, 31, 11, 34]])

In [13]:
# array[num_Row, num_column]

x2[0,2] #31

np.int64(31)

------------------------

------------------------

## The End !.