# Numpy

## Slicing in 1D array.

In [1]:
import numpy as np

In [3]:
x = np.arange(10) #as we know create 1D array . in range from 0 to 10.

In [4]:
x[0:2] # in python indexing start from 0.

array([0, 1])

In [5]:
x[0:] # from index 0 To the End 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[:] # from first to end.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[::2] # x[start: end: step]

array([0, 2, 4, 6, 8])

## The End 👍.