# Numpy

## Slicing multi Array.

- multi dimentional -> from **2D or more**

In [1]:
import numpy as np

In [5]:
x2 = np.array([[1,2,3,4,5],[1,3,21,32,23],[33,40,43,21,11]]) # this is 2D array. | with 3Rows & 5Colums

x2

array([[ 1,  2,  3,  4,  5],
       [ 1,  3, 21, 32, 23],
       [33, 40, 43, 21, 11]])

**How can i do**

array[num_row , num_column]

In [6]:
x2[0,1] #return ->2

np.int64(2)

In [7]:
#[1, 3, 21]
#[33,40,43]
x2[1:,0:3] 

array([[ 1,  3, 21],
       [33, 40, 43]])

In [15]:
x2[::2,::2]

array([[ 1,  3,  5],
       [33, 43, 11]])

# The End 👍🏻.